hello: ENC[AES256_GCM,data:b4LsvYhqbNj32ztajak6Yw==,iv:zWYgHGg8kGmeJNSfFkNSJiTHBAGkL+fgG1Vqu1KDMA8=,tag:huIQNJK3+EbAj/Pg9ygXfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rwvhnhhz00uxzr7vcvm2huwckdx60x926emt9e0xvzj2gz4mhe9qq8vtee
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQVl2N2dZV1NCVHp2RmIz
            QXNBeHlqUlJuak5MbVdzY05CTW5nM29Td1dNClhEc2E2U3hrOUJublpIS1h5cStw
            NTY4VExqUFMvZ3RRZC83ODdObzltRkEKLS0tIHRxR2M3MnIxdHBpUFdRNjdPbHo3
            anU1eHpiaWtXbWdybEhib08rRWpJaUEKPNz9XT3mTTMHf7HgvAC6Tw0WZeatBGFF
            PFqETo9XEJbIyJ6+n6a0mEW/kD9EgPNgwg3LSWZU5ddANdsEIXQ2wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-12T17:22:40Z"
    mac: ENC[AES256_GCM,data:RIUkUTZ1KnvQkJ7wEUU4wt1NoLg513r5fRtZZh8ubrOyGrtw21o3gD4Zf44x3OM9jQapzATem0YoE6KTHaGajYbbaHZ7B8keMNUF1WPZ1PDnjCWjKZD5ZkG0lXBFevLmzD1h2W2ztDsooOFAdjlFJPZlMGxeaceHvA2eJCRGhfE=,iv:j7ITPHiGclvVAdx1MxURyr8el6VoZ/SpvdBwfs+T8KI=,tag:940zUXYn0CWVsAg45C6zcw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
