plausible:
    adminPassword: ENC[AES256_GCM,data:8sQ/gcHeXFQ=,iv:rJJLy4NRWmyePPAFBdiLOgqTeqLPFx4W9xOGOwWBWrw=,tag:cImyqbcKCm+wIwWuu8yL1g==,type:str]
    releaseCookie: ENC[AES256_GCM,data:aQc7gbi0Yns=,iv:os4XPS+tA5iOpDjemlxt+03HGjk2kw8rdxXIjxAD2fE=,tag:wjGp5ZNZTEgsHjqDO1611g==,type:str]
    secretKeybase: ENC[AES256_GCM,data:ErLxz9CXfwo=,iv:Dt53PEnSFJAYckX9wmFRUyP7cyxOWWrbJTu/xQcwluM=,tag:9yBdQfQeAjoKqBrgMEH9UA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rwvhnhhz00uxzr7vcvm2huwckdx60x926emt9e0xvzj2gz4mhe9qq8vtee
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVGFZMXMveDk2Ny9ZazV3
            dU5qWkdKY05wdzlzSVpZNGNzR2syemZBNDBBCmVaQU9kTUtKQndKRTB2b3dWOVg4
            QnU2RTJTY2VkQTJhV2Y0TWx3bWs3aEEKLS0tIGV5S1NpVXZmQ0h6d3BIRWgxTHQ3
            NmxJRTFwbEVOTVQ2WWVVVDQvUGZ4UWcKpWtXlheV7FvP8jQkvnSwtO/DKIM2/xZj
            iTN41Q0zMymZ5y9hBawG80d+G77LrhQSsT95zc6xZuHdjugAYnARWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-13T21:00:14Z"
    mac: ENC[AES256_GCM,data:DtRPhp2oq7+u1LhtVf7BjrbAOCzGRPFTxsGj2OywpxRnzrS0Q2QyxmDe910R9ow6N5s/4iSVdehfWXG6cTxfC8uCvmLnZHGq6GF9rd//0K8KOFI1LttACWH0x3pCJnt+zoGsJhB3w0IK9yc6OH4DwgUT+aihOGgh9z6V8Scuqr8=,iv:kxZ5bCAiFgfPef4xfQDl+T5gKoZASqndCYGU00GtkIY=,tag:bLMKXkhxWiiIMPJVgWQh5Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
